ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'SERVICE_INCOME';

ALTER TABLE "QuickCashTransferDetail"
  ADD COLUMN IF NOT EXISTS "purpose" TEXT NOT NULL DEFAULT 'TRANSFER',
  ADD COLUMN IF NOT EXISTS "serviceName" TEXT;
