"use client";

import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { EmptyState, StatusBadge, Surface } from "@/components/ui";

export type Gateway={id:string;gatewayName:string;defaultChargeRate:string;defaultChargeType:string;isActive:boolean};
export type Provider={id:string;name:string;providerType:string;supportsAeps:boolean;aepsCommissionRate:string;isActive:boolean;gateways:Gateway[]};
export type Term={id:string;name:string;durationValue:number;durationUnit:string;defaultCommissionType:string;defaultCommissionRate:string;isActive:boolean};
export type Category={id:string;name:string;expenseUsage:string;isActive:boolean};
export type Rule={id:string;customerId:string|null;providerId:string|null;gatewayId:string|null;paymentTermId:string|null;transactionType:string;commissionType:string;commissionRate:string;isActive:boolean;paymentTerm:Term|null};

type Area="payments"|"terms"|"commission"|"expenses";
type ProviderTab="gateways"|"charges"|"conditions";
type IconName="wallet"|"percent"|"clock"|"receipt"|"search"|"plus"|"chevron"|"info";
type Props={providers:Provider[];terms:Term[];categories:Category[];rules:Rule[];onCreate:(kind:"provider"|"gateway"|"term"|"category"|"rule",providerId?:string)=>void;onEditProvider:(p:Provider)=>void;onEditGateway:(g:Gateway)=>void;onEditTerm:(t:Term)=>void;onEditCategory:(c:Category)=>void;onEditRule:(r:Rule)=>void;onToggle:(path:string,isActive:boolean,label:string)=>void;onQuickAddCategory:(name:string)=>void;onSaveCashTransferDefault:(rate:number)=>Promise<void>;onSaveCardSwipeDefault:(rate:number)=>Promise<void>;onSaveAepsDefault:(rate:number)=>Promise<void>};

const primary="app-primary-button min-h-10 px-3.5 text-xs font-bold sm:min-h-11 sm:px-4 sm:text-sm";
const secondary="app-secondary-button min-h-9 px-3 text-[11px] font-bold";
const recommended=["Office Supplies","Travel & Transport","Utilities","Rent & Maintenance","Salary & Wages","Marketing","Bank & Gateway Fees","Internet & Phone","Repairs & Maintenance","Professional Fees","Taxes & Licenses","Meals & Staff Welfare","Other"];

function Icon({name,className="h-5 w-5"}:{name:IconName;className?:string}) {
 const common={fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
 const paths:Record<IconName,ReactNode>={wallet:<><path d="M4 7h16v12H4z"/><path d="M4 8V5h13"/><path d="M15 12h7v4h-7z"/></>,percent:<><circle cx="7" cy="7" r="2"/><circle cx="17" cy="17" r="2"/><path d="m19 5-14 14"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,receipt:<><path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6M9 16h4"/></>,search:<><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,chevron:<path d="m9 18 6-6-6-6"/>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>};
 return <svg viewBox="0 0 24 24" className={className} aria-hidden="true" {...common}>{paths[name]}</svg>;
}

function humanType(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function charge(g:Gateway){return g.defaultChargeType==="PERCENTAGE"?rateLabel(g.defaultChargeRate)+"%":"₹"+Number(g.defaultChargeRate).toFixed(2);}
function duration(t:Term){return t.durationValue===0?"Instant":t.durationValue+" "+t.durationUnit.toLowerCase();}
function rateLabel(value:string|number){return Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:4});}


function ServiceDefault({label,rate,onSave}:{label:string;rate:number;onSave:(rate:number)=>Promise<void>}){
 const [value,setValue]=useState(rateLabel(rate)),[saving,setSaving]=useState(false);
 return <div className="flex flex-col gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4 sm:flex-row sm:items-center sm:justify-between">
  <div><p className="text-sm font-black">{label}</p><p className="mt-1 text-xs text-[var(--text-muted)]">Default commission</p></div>
  <div className="flex items-center gap-2">
   <div className="relative w-28"><input aria-label={label+" default commission percentage"} className="min-h-10 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 pr-7 text-right text-sm font-black outline-none focus:border-[var(--accent)]" type="number" min="0" max="100" step="0.0001" value={value} onChange={e=>setValue(e.target.value)}/><span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs text-[var(--text-muted)]">%</span></div>
   <button type="button" disabled={saving} onClick={async()=>{setSaving(true);try{await onSave(Number(value||0));}finally{setSaving(false);}}} className={primary}>{saving?"Saving…":"Save"}</button>
  </div>
 </div>;
}
function Metric({icon,label,value,tone}:{icon:IconName;label:string;value:number;tone:string}) {
 return <Surface className="flex min-w-0 items-center gap-3 p-3.5 sm:p-4"><span className={"grid h-11 w-11 shrink-0 place-items-center rounded-2xl "+tone}><Icon name={icon}/></span><div className="min-w-0"><p className="text-xl font-black tracking-[-.03em] sm:text-2xl">{value}</p><p className="truncate text-xs font-bold">{label}</p></div></Surface>;
}

export function SettingsWorkspace({providers,terms,categories,rules,onCreate,onEditProvider,onEditGateway,onEditTerm,onEditCategory,onEditRule,onToggle,onQuickAddCategory,onSaveCashTransferDefault,onSaveCardSwipeDefault,onSaveAepsDefault}:Props){
 const [area,setArea]=useState<Area>("payments"),[providerTab,setProviderTab]=useState<ProviderTab>("gateways"),[selectedId,setSelectedId]=useState(""),[query,setQuery]=useState("");
 const selected=providers.find(p=>p.id===selectedId)||providers.find(p=>p.isActive)||providers[0]||null;
 const activeProviders=providers.filter(p=>p.isActive).length,activeGateways=providers.flatMap(p=>p.gateways).filter(g=>g.isActive).length,activeTerms=terms.filter(t=>t.isActive).length,activeCategories=categories.filter(c=>c.isActive).length;
 const filtered=useMemo(()=>providers.filter(p=>!query.trim()||p.name.toLowerCase().includes(query.trim().toLowerCase())||p.gateways.some(g=>g.gatewayName.toLowerCase().includes(query.trim().toLowerCase()))||(p.supportsAeps&&"aadhaar withdrawal aeps".includes(query.trim().toLowerCase()))),[providers,query]);
 const selectedRules=rules.filter(r=>r.providerId===selected?.id),missing=recommended.filter(name=>!categories.some(c=>c.name.toLowerCase()===name.toLowerCase())).slice(0,8);
 const cashTransferDefaultRule=rules.find(r=>r.transactionType==="CASH_TRANSFER"&&!r.customerId&&!r.providerId&&!r.gatewayId&&!r.paymentTermId);
 const cardSwipeDefaultRule=rules.find(r=>r.transactionType==="CARD_SWIPE"&&!r.customerId&&!r.providerId&&!r.gatewayId&&!r.paymentTermId);
 const aepsDefaultRule=rules.find(r=>r.transactionType==="AEPS_WITHDRAWAL"&&!r.customerId&&!r.providerId&&!r.gatewayId&&!r.paymentTermId);
 const overrideRules=rules.filter(r=>r.id!==cashTransferDefaultRule?.id&&r.id!==cardSwipeDefaultRule?.id&&r.id!==aepsDefaultRule?.id);
 function commissionLabel(p:Provider){const v=rules.filter(r=>r.isActive&&r.providerId===p.id&&r.commissionType==="PERCENTAGE").map(r=>Number(r.commissionRate)).filter(Number.isFinite);if(!v.length)return "Uses defaults";const min=Math.min(...v),max=Math.max(...v);return min===max?rateLabel(min)+"%":rateLabel(min)+"–"+rateLabel(max)+"%";}

 const tabs=[["payments","Payment Providers","wallet"],["terms","Payment Terms","clock"],["commission","Commission Rules","percent"],["expenses","Expense Categories","receipt"]] as const;
 return <div className="space-y-4 sm:space-y-5">
  <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="mb-1.5 text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Configuration</p><h1 className="text-[1.7rem] font-black tracking-[-.04em] sm:text-[2rem]">Payment Configuration</h1></div><div className="flex items-start gap-2 rounded-2xl border border-indigo-200 bg-indigo-50/80 px-3.5 py-3 text-xs leading-5 text-indigo-700 xl:max-w-[390px]"><Icon name="info" className="mt-0.5 h-4 w-4 shrink-0"/><span>Future transactions only.</span></div></div>
  <div className="overflow-x-auto pb-1"><div className="grid min-w-[680px] grid-cols-4 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-1">{tabs.map(([id,label,icon])=><button key={id} type="button" onClick={()=>setArea(id)} className={"flex min-h-11 items-center justify-center gap-2 rounded-xl px-3 text-xs font-bold transition sm:text-sm "+(area===id?"bg-[var(--accent)] text-white shadow-[0_8px_22px_color-mix(in_srgb,var(--accent)_24%,transparent)]":"text-[var(--text-muted)] hover:bg-[var(--surface)] hover:text-[var(--text)]")}><Icon name={icon} className="h-4 w-4"/>{label}</button>)}</div></div>
  <div className="grid grid-cols-2 gap-2.5 lg:grid-cols-4 lg:gap-3"><Metric icon="wallet" label="Payment providers" value={activeProviders} tone="bg-indigo-50 text-indigo-600"/><Metric icon="percent" label="Active gateways" value={activeGateways} tone="bg-emerald-50 text-emerald-600"/><Metric icon="clock" label="Payment terms" value={activeTerms} tone="bg-amber-50 text-amber-700"/><Metric icon="receipt" label="Expense categories" value={activeCategories} tone="bg-rose-50 text-rose-600"/></div>

  {area==="payments"?<div className="grid items-start gap-4 xl:grid-cols-[minmax(360px,.78fr)_minmax(0,1.22fr)]">
   <Surface className="overflow-hidden"><div className="border-b border-[var(--border)] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-black tracking-[-.02em]">Payment Providers</h2></div><button type="button" onClick={()=>onCreate("provider")} className={primary}><span className="inline-flex items-center gap-1.5"><Icon name="plus" className="h-4 w-4"/>Provider</span></button></div><div className="relative mt-4"><Icon name="search" className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] pl-10 pr-3 text-sm outline-none focus:border-[color-mix(in_srgb,var(--accent)_45%,var(--border))]" placeholder="Search provider or gateway…"/></div></div>
   <div className="max-h-[670px] space-y-1.5 overflow-y-auto p-2.5 sm:p-3">{filtered.map(p=><button key={p.id} type="button" onClick={()=>{setSelectedId(p.id);setProviderTab("gateways");}} className={"group flex w-full items-center gap-3 rounded-2xl border px-3 py-3 text-left transition "+(selected?.id===p.id?"border-[color-mix(in_srgb,var(--accent)_28%,var(--border))] bg-[color-mix(in_srgb,var(--accent-soft)_64%,var(--surface))] shadow-[0_8px_22px_color-mix(in_srgb,var(--accent)_8%,transparent)]":"border-transparent hover:border-[var(--border)] hover:bg-[var(--surface-soft)]")}><span className={"grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-black "+(selected?.id===p.id?"bg-[var(--accent)] text-white":"bg-[var(--surface-soft)] text-[var(--accent)] ring-1 ring-[var(--border)]")}>{p.name.trim().slice(0,2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><strong className="truncate text-sm">{p.name}</strong><span className={"h-2 w-2 shrink-0 rounded-full "+(p.isActive?"bg-emerald-500":"bg-slate-300")}/></span><span className="mt-0.5 block truncate text-[11px] text-[var(--text-muted)]">{humanType(p.providerType)} · {p.gateways.length} gateway{p.gateways.length===1?"":"s"}{p.supportsAeps?" · Aadhaar":""}</span></span><span className="hidden shrink-0 text-right sm:block"><span className="block text-xs font-black">{commissionLabel(p)}</span><span className="text-[10px] text-[var(--text-muted)]">Commission</span></span><Icon name="chevron" className="h-4 w-4 shrink-0 text-[var(--text-muted)]"/></button>)}{!filtered.length?<EmptyState title="No providers found" description="Try another search or add a new payment provider."/>:null}</div></Surface>
   {selected?<Surface className="overflow-hidden"><div className="border-b border-[var(--border)] p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[linear-gradient(145deg,var(--accent),#7c3aed)] text-lg font-black text-white shadow-[0_12px_28px_color-mix(in_srgb,var(--accent)_26%,transparent)]">{selected.name.trim().slice(0,2).toUpperCase()}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-black tracking-[-.03em]">{selected.name}</h2><StatusBadge tone={selected.isActive?"emerald":"slate"}>{selected.isActive?"Active":"Inactive"}</StatusBadge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{humanType(selected.providerType)} · {selected.gateways.filter(g=>g.isActive).length} active gateways{selected.supportsAeps?" · Aadhaar withdrawal":""}</p></div></div><div className="flex gap-2"><button type="button" onClick={()=>onEditProvider(selected)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/providers/"+selected.id,selected.isActive,selected.name)} className={secondary}>{selected.isActive?"Retire":"Activate"}</button></div></div><div className="mt-5 flex gap-1 overflow-x-auto border-b border-[var(--border)]">{([["gateways","Gateways ("+selected.gateways.length+")"],["charges","Commission & charges"],["conditions","Terms & conditions"]] as [ProviderTab,string][]).map(([id,label])=><button key={id} type="button" onClick={()=>setProviderTab(id)} className={"whitespace-nowrap border-b-2 px-3 py-2.5 text-xs font-bold transition "+(providerTab===id?"border-[var(--accent)] text-[var(--accent)]":"border-transparent text-[var(--text-muted)] hover:text-[var(--text)]")}>{label}</button>)}</div></div>
   {providerTab==="gateways"?<div className="p-4 sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-black">Gateways</h3></div><button type="button" onClick={()=>onCreate("gateway",selected.id)} className={primary}><span className="inline-flex items-center gap-1.5"><Icon name="plus" className="h-4 w-4"/>Gateway</span></button></div>
    {selected.gateways.length?<div className="overflow-hidden rounded-2xl border border-[var(--border)]"><div className="hidden grid-cols-[minmax(0,1.5fr)_.7fr_.8fr_.65fr_auto] gap-3 bg-[var(--surface-soft)] px-4 py-2.5 text-[10px] font-extrabold uppercase tracking-[.08em] text-[var(--text-muted)] md:grid"><span>Gateway</span><span>Charge type</span><span>Default charge</span><span>Status</span><span>Action</span></div><div className="divide-y divide-[var(--border)]">{selected.gateways.map(g=><div key={g.id} className={"grid gap-3 px-4 py-3.5 md:grid-cols-[minmax(0,1.5fr)_.7fr_.8fr_.65fr_auto] md:items-center "+(!g.isActive?"opacity-55":"")}><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-xs font-black text-[var(--accent)]">{g.gatewayName.trim().slice(0,1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{g.gatewayName}</p><p className="mt-0.5 text-[10px] text-[var(--text-muted)] md:hidden">Default {charge(g)}</p></div></div><span className="hidden text-xs font-semibold text-[var(--text-muted)] md:block">{g.defaultChargeType==="PERCENTAGE"?"Percentage":"Fixed"}</span><span className="hidden text-sm font-black md:block">{charge(g)}</span><div className="hidden md:block"><StatusBadge tone={g.isActive?"emerald":"slate"}>{g.isActive?"Active":"Inactive"}</StatusBadge></div><div className="flex gap-2 md:justify-end"><button type="button" onClick={()=>onEditGateway(g)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/providers/gateways/"+g.id,g.isActive,g.gatewayName)} className={secondary}>{g.isActive?"Retire":"Activate"}</button></div></div>)}</div></div>:<EmptyState title="No gateways configured" description="Add the first processing gateway for this provider."/>}
    </div>:null}
   {providerTab==="charges"?<div className="space-y-4 p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[var(--text-muted)]">Provider commission</p><p className="mt-2 text-2xl font-black">{commissionLabel(selected)}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[var(--text-muted)]">Gateway charges</p><p className="mt-2 text-2xl font-black">{selected.gateways.filter(g=>g.isActive).length}</p></div><div className={"rounded-2xl border p-4 "+(selected.supportsAeps?"border-emerald-200 bg-emerald-50/70":"border-[var(--border)] bg-[var(--surface-soft)]")}><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[var(--text-muted)]">Aadhaar withdrawal</p><p className={"mt-2 text-2xl font-black "+(selected.supportsAeps?"text-emerald-700":"text-[var(--text-muted)]")}>{selected.supportsAeps?rateLabel(selected.aepsCommissionRate)+"%":"Off"}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{selected.supportsAeps?"Default commission":"Not supported"}</p></div></div><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Commission overrides</h3></div><button type="button" onClick={()=>onCreate("rule",selected.id)} className={primary}>+ Rule</button></div>
    {selectedRules.length?<div className="space-y-2">{selectedRules.map(r=><div key={r.id} className={"flex flex-col gap-3 rounded-2xl border border-[var(--border)] p-3.5 sm:flex-row sm:items-center sm:justify-between "+(!r.isActive?"opacity-55":"")}><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold">{r.transactionType.replaceAll("_"," ")}</p><StatusBadge tone={r.isActive?"emerald":"slate"}>{r.isActive?"Active":"Inactive"}</StatusBadge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{Number(r.commissionRate)}{r.commissionType==="PERCENTAGE"?"%":" fixed"} · {r.paymentTerm?.name||"Any term"} · {r.gatewayId?"Gateway-specific":"Any gateway"}</p></div><div className="flex gap-2"><button type="button" onClick={()=>onEditRule(r)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/settings/commission-rules/"+r.id,r.isActive,"commission rule")} className={secondary}>{r.isActive?"Retire":"Activate"}</button></div></div>)}</div>:<EmptyState title="No provider-specific commission rules" description="Payment-term defaults will be used until you add an override."/>}</div>:null}
   {providerTab==="conditions"?<div className="space-y-4 p-4 sm:p-5"><div><h3 className="font-black">Payment terms & conditions</h3></div><div className="grid gap-3 sm:grid-cols-2">{terms.filter(t=>t.isActive).map(t=><div key={t.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">{t.name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{duration(t)}</p></div><strong className="text-sm text-[var(--accent)]">{Number(t.defaultCommissionRate).toFixed(2)}%</strong></div></div>)}</div>{!terms.some(t=>t.isActive)?<EmptyState title="No active payment terms" description="Add a term such as Instant, 1 day, 3 days or 7 days."/>:null}<button type="button" onClick={()=>setArea("terms")} className={secondary}>Manage payment terms</button></div>:null}
   </Surface>:<EmptyState title="No payment providers configured" description="Add a provider first, then configure its gateways and charges."/>}
  </div>:null}
  {area==="terms"?<div className="grid items-start gap-4">
   <Surface className="overflow-hidden"><div className="flex items-start justify-between gap-3 border-b border-[var(--border)] p-4 sm:p-5"><div><h2 className="text-base font-black">Payment terms</h2></div><button type="button" onClick={()=>onCreate("term")} className={primary}>+ Term</button></div><div className="grid gap-2.5 p-3 sm:grid-cols-2 sm:p-4">{terms.map(t=><div key={t.id} className={"rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4 "+(!t.isActive?"opacity-55":"")}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black">{t.name}</p><StatusBadge tone={t.isActive?"emerald":"slate"}>{t.isActive?"Active":"Inactive"}</StatusBadge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{duration(t)}</p></div><span className="rounded-xl bg-[var(--accent-soft)] px-2.5 py-1.5 text-sm font-black text-[var(--accent)]">{Number(t.defaultCommissionRate).toFixed(2)}%</span></div><p className="mt-3 text-[11px] text-[var(--text-muted)]">Default commission</p><div className="mt-4 flex gap-2"><button type="button" onClick={()=>onEditTerm(t)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/settings/payment-terms/"+t.id,t.isActive,t.name)} className={secondary}>{t.isActive?"Retire":"Activate"}</button></div></div>)}</div></Surface>
   
  </div>:null}

  {area==="commission"?<div className="grid items-start gap-4">
   <Surface className="overflow-hidden">
    <div className="border-b border-[var(--border)] p-4 sm:p-5"><h2 className="text-base font-black">Service defaults</h2></div>
    <div className="grid gap-3 p-3 sm:p-4 lg:grid-cols-3"><ServiceDefault label="Card Swipe" key={(cardSwipeDefaultRule?.id||"card-new")+":"+(cardSwipeDefaultRule?.commissionRate||"0")} rate={Number(cardSwipeDefaultRule?.commissionRate||0)} onSave={onSaveCardSwipeDefault}/><ServiceDefault label="Cash Transfer" key={(cashTransferDefaultRule?.id||"cash-new")+":"+(cashTransferDefaultRule?.commissionRate||"0")} rate={Number(cashTransferDefaultRule?.commissionRate||0)} onSave={onSaveCashTransferDefault}/><ServiceDefault label="AEPS" key={(aepsDefaultRule?.id||"aeps-new")+":"+(aepsDefaultRule?.commissionRate||"0")} rate={Number(aepsDefaultRule?.commissionRate||0)} onSave={onSaveAepsDefault}/></div>
   </Surface>
   <Surface className="overflow-hidden"><div className="flex items-start justify-between gap-3 border-b border-[var(--border)] p-4 sm:p-5"><div><h2 className="text-base font-black">Commission overrides</h2></div><button type="button" onClick={()=>onCreate("rule")} className={primary}>+ Rule</button></div><div className="space-y-2 p-3 sm:p-4">{overrideRules.map(r=>{const provider=providers.find(p=>p.id===r.providerId);const gateway=provider?.gateways.find(g=>g.id===r.gatewayId);return <div key={r.id} className={"rounded-2xl border border-[var(--border)] p-4 "+(!r.isActive?"opacity-55":"")}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-black">{r.transactionType.replaceAll("_"," ")}</p><StatusBadge tone={r.isActive?"emerald":"slate"}>{r.isActive?"Active":"Inactive"}</StatusBadge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{provider?.name||"Any provider"} · {gateway?.gatewayName||"Any gateway"} · {r.paymentTerm?.name||"Any term"} · {r.customerId?"Specific customer":"Any customer"}</p></div><div className="flex items-center gap-2"><span className="rounded-xl bg-[var(--accent-soft)] px-3 py-2 text-sm font-black text-[var(--accent)]">{Number(r.commissionRate)}{r.commissionType==="PERCENTAGE"?"%":" fixed"}</span><button type="button" onClick={()=>onEditRule(r)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/settings/commission-rules/"+r.id,r.isActive,"commission rule")} className={secondary}>{r.isActive?"Retire":"Activate"}</button></div></div></div>;})}{!overrideRules.length?<EmptyState title="No commission overrides"/>:null}</div></Surface>
  </div>:null}


  {area==="expenses"?<div className="space-y-4">
   <Surface className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row sm:items-start sm:justify-between sm:p-5"><div><h2 className="text-base font-black">Expense Categories</h2></div><button type="button" onClick={()=>onCreate("category")} className={primary}>+ Category</button></div><div className="grid gap-2.5 p-3 sm:grid-cols-2 sm:p-4 lg:grid-cols-3 xl:grid-cols-4">{categories.map((cat,index)=><div key={cat.id} className={"group rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 transition hover:-translate-y-0.5 hover:shadow-lg "+(!cat.isActive?"opacity-55":"")}><div className="flex items-start gap-3"><span className={"grid h-10 w-10 shrink-0 place-items-center rounded-xl "+(["bg-indigo-50 text-indigo-600","bg-emerald-50 text-emerald-600","bg-amber-50 text-amber-700","bg-rose-50 text-rose-600"][index%4])}><Icon name="receipt" className="h-4 w-4"/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-black">{cat.name}</p>{cat.isActive?<span className="h-2 w-2 shrink-0 rounded-full bg-emerald-500"/>:null}</div><p className="mt-1 text-[11px] capitalize text-[var(--text-muted)]">{cat.expenseUsage==="MIXED"?"Business & personal":cat.expenseUsage.toLowerCase()}</p></div></div><div className="mt-4 flex gap-2"><button type="button" onClick={()=>onEditCategory(cat)} className={secondary}>Edit</button><button type="button" onClick={()=>onToggle("/settings/expense-categories/"+cat.id,cat.isActive,cat.name)} className={secondary}>{cat.isActive?"Retire":"Activate"}</button></div></div>)}</div></Surface>
   {missing.length?<Surface className="p-4 sm:p-5"><h3 className="font-black">Suggested everyday categories</h3><div className="mt-4 flex flex-wrap gap-2">{missing.map(name=><button key={name} type="button" onClick={()=>onQuickAddCategory(name)} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] px-3 text-xs font-bold transition hover:border-[color-mix(in_srgb,var(--accent)_28%,var(--border))] hover:bg-[var(--accent-soft)] hover:text-[var(--accent)]"><Icon name="plus" className="h-3.5 w-3.5"/>{name}</button>)}</div></Surface>:null}
  </div>:null}
 </div>;
}
